event = {

    [NO_EVENT] = 0,
    [PLAYER_SET_WEAPON_KNIFE] = 1,
    [PLAYER_SET_WEAPON_GUN] = 2,
    [PLAYER_SET_WEAPON_SECONDARY] = 3,
    [PLAYER_START_MOVING_FORWARD] = 4,
    [PLAYER_START_MOVING_BACKWARD] = 5,
    [PLAYER_STOP_MOVING] = 6,
    [PLAYER_START_ROTATING_RIGHT] = 7,
    [PLAYER_START_ROTATING_LEFT] = 8,
    [PLAYER_STOP_ROTATING] = 9,
    [PLAYER_SHOOT] = 10,
    [PLAYER_STOP_SHOOTING] = 11,
    [PLAYER_START_OPENING_DOOR] = 12,
    [PLAYER_STOP_OPENING_DOOR] = 13
}